# Generated by Django 4.0 on 2021-12-08 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PreentregaApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mastil',
            old_name='numero',
            new_name='largo',
        ),
    ]
